openapi: 3.0.1
info:
  title: monster-chaotic-nymph
  x-cortex-tag: monster-chaotic-nymph
  x-cortex-custom-metadata:
    alignment: chaotic-good
    type: fey
    challenge_rating: 3
    legendary: false
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-chaotic-nymph
      alias: github-token
